#Load in the draws prior to running this code

#Create the arrays to produce counts in the algorithm

set.seed(3101301)

pot1 = c("ITNap",
         "PORPor",
         "GERBay",
         "UKTot",
         "UKChe",
         "SPARM",
         "UKMC",
         "PORBen")
pot2 = c("UKLiv",
         "BELCB",
         "ITIM",
         "GERFra",
         "ITMil",
         "GERLei",
         "GERDort",
         "FRAPSG")




incMatrixU <- function(i, j) {
  countMatrixu[i, j] <<- countMatrix[i, j] + 1
  return(0)
}
incMatrix <- function(i, j) {
  countMatrix[i, j] <<- countMatrix[i, j] + 1
  return(0)
}
#start of algorithm

for (j in 1:100) {
  countMatrixu = matrix(0,
                        nrow = 8,
                        ncol = 8,
                        dimnames = list(pot1, pot2))
  countMatrix = matrix(0,
                       nrow = 8,
                       ncol = 8,
                       dimnames = list(pot1, pot2))
  
  m = length(countMatrix)
  
  k = sample(1:64, 1) #randomly sample number of indices to use
  
  indices = sample(1:64, k)
  
  TVEstimate = c()
  
  for (i in 1:length(drawsS)) {
    mapply(incMatrixU, drawsU[[i]][1, 1, ], drawsU[[i]][1, 2, ])
    mapply(incMatrix, drawsS[[i]][1, 1, ], drawsS[[i]][1, 2, ])
    
    probArrayU = countMatrixu / i
    probArrayF = countMatrix / i
    
    
    diffarray = abs(probArrayU - probArrayF)
    
    estimate = 64 * (sum(diffarray[indices]) / k) #use the TV estimate given in the report on the given indices
    
    TVEstimate[i] = estimate
    
  }
  assign(paste("TVEstimate", j, sep = ""), TVEstimate, envir = .GlobalEnv)
  print(paste("Simulation", j))
}

#Create vectors of the minimum, maximum and mean for each element

TVMin = pmin(
  TVEstimate1,
  TVEstimate2,
  TVEstimate3,
  TVEstimate4,
  TVEstimate5,
  TVEstimate6,
  TVEstimate7,
  TVEstimate8,
  TVEstimate9,
  TVEstimate10,
  TVEstimate11,
  TVEstimate12,
  TVEstimate13,
  TVEstimate14,
  TVEstimate15,
  TVEstimate16,
  TVEstimate17,
  TVEstimate18,
  TVEstimate19,
  TVEstimate20,
  TVEstimate21,
  TVEstimate22,
  TVEstimate23,
  TVEstimate24,
  TVEstimate25,
  TVEstimate26,
  TVEstimate27,
  TVEstimate28,
  TVEstimate29,
  TVEstimate30,
  TVEstimate31,
  TVEstimate32,
  TVEstimate33,
  TVEstimate34,
  TVEstimate35,
  TVEstimate36,
  TVEstimate37,
  TVEstimate38,
  TVEstimate39,
  TVEstimate40,
  TVEstimate41,
  TVEstimate42,
  TVEstimate43,
  TVEstimate44,
  TVEstimate45,
  TVEstimate46,
  TVEstimate47,
  TVEstimate48,
  TVEstimate49,
  TVEstimate50,
  TVEstimate51,
  TVEstimate52,
  TVEstimate53,
  TVEstimate54,
  TVEstimate55,
  TVEstimate56,
  TVEstimate57,
  TVEstimate58,
  TVEstimate59,
  TVEstimate60,
  TVEstimate61,
  TVEstimate62,
  TVEstimate63,
  TVEstimate64,
  TVEstimate65,
  TVEstimate66,
  TVEstimate67,
  TVEstimate68,
  TVEstimate69,
  TVEstimate70,
  TVEstimate71,
  TVEstimate72,
  TVEstimate73,
  TVEstimate74,
  TVEstimate75,
  TVEstimate76,
  TVEstimate77,
  TVEstimate78,
  TVEstimate79,
  TVEstimate80,
  TVEstimate81,
  TVEstimate82,
  TVEstimate83,
  TVEstimate84,
  TVEstimate85,
  TVEstimate86,
  TVEstimate87,
  TVEstimate88,
  TVEstimate89,
  TVEstimate90,
  TVEstimate91,
  TVEstimate92,
  TVEstimate93,
  TVEstimate94,
  TVEstimate95,
  TVEstimate96,
  TVEstimate97,
  TVEstimate98,
  TVEstimate99,
  TVEstimate100
)
TVMax = pmax(
  TVEstimate1,
  TVEstimate2,
  TVEstimate3,
  TVEstimate4,
  TVEstimate5,
  TVEstimate6,
  TVEstimate7,
  TVEstimate8,
  TVEstimate9,
  TVEstimate10,
  TVEstimate11,
  TVEstimate12,
  TVEstimate13,
  TVEstimate14,
  TVEstimate15,
  TVEstimate16,
  TVEstimate17,
  TVEstimate18,
  TVEstimate19,
  TVEstimate20,
  TVEstimate21,
  TVEstimate22,
  TVEstimate23,
  TVEstimate24,
  TVEstimate25,
  TVEstimate26,
  TVEstimate27,
  TVEstimate28,
  TVEstimate29,
  TVEstimate30,
  TVEstimate31,
  TVEstimate32,
  TVEstimate33,
  TVEstimate34,
  TVEstimate35,
  TVEstimate36,
  TVEstimate37,
  TVEstimate38,
  TVEstimate39,
  TVEstimate40,
  TVEstimate41,
  TVEstimate42,
  TVEstimate43,
  TVEstimate44,
  TVEstimate45,
  TVEstimate46,
  TVEstimate47,
  TVEstimate48,
  TVEstimate49,
  TVEstimate50,
  TVEstimate51,
  TVEstimate52,
  TVEstimate53,
  TVEstimate54,
  TVEstimate55,
  TVEstimate56,
  TVEstimate57,
  TVEstimate58,
  TVEstimate59,
  TVEstimate60,
  TVEstimate61,
  TVEstimate62,
  TVEstimate63,
  TVEstimate64,
  TVEstimate65,
  TVEstimate66,
  TVEstimate67,
  TVEstimate68,
  TVEstimate69,
  TVEstimate70,
  TVEstimate71,
  TVEstimate72,
  TVEstimate73,
  TVEstimate74,
  TVEstimate75,
  TVEstimate76,
  TVEstimate77,
  TVEstimate78,
  TVEstimate79,
  TVEstimate80,
  TVEstimate81,
  TVEstimate82,
  TVEstimate83,
  TVEstimate84,
  TVEstimate85,
  TVEstimate86,
  TVEstimate87,
  TVEstimate88,
  TVEstimate89,
  TVEstimate90,
  TVEstimate91,
  TVEstimate92,
  TVEstimate93,
  TVEstimate94,
  TVEstimate95,
  TVEstimate96,
  TVEstimate97,
  TVEstimate98,
  TVEstimate99,
  TVEstimate100
)
TVMean = colMeans(
  rbind(
    TVEstimate1,
    TVEstimate2,
    TVEstimate3,
    TVEstimate4,
    TVEstimate5,
    TVEstimate6,
    TVEstimate7,
    TVEstimate8,
    TVEstimate9,
    TVEstimate10,
    TVEstimate11,
    TVEstimate12,
    TVEstimate13,
    TVEstimate14,
    TVEstimate15,
    TVEstimate16,
    TVEstimate17,
    TVEstimate18,
    TVEstimate19,
    TVEstimate20,
    TVEstimate21,
    TVEstimate22,
    TVEstimate23,
    TVEstimate24,
    TVEstimate25,
    TVEstimate26,
    TVEstimate27,
    TVEstimate28,
    TVEstimate29,
    TVEstimate30,
    TVEstimate31,
    TVEstimate32,
    TVEstimate33,
    TVEstimate34,
    TVEstimate35,
    TVEstimate36,
    TVEstimate37,
    TVEstimate38,
    TVEstimate39,
    TVEstimate40,
    TVEstimate41,
    TVEstimate42,
    TVEstimate43,
    TVEstimate44,
    TVEstimate45,
    TVEstimate46,
    TVEstimate47,
    TVEstimate48,
    TVEstimate49,
    TVEstimate50,
    TVEstimate51,
    TVEstimate52,
    TVEstimate53,
    TVEstimate54,
    TVEstimate55,
    TVEstimate56,
    TVEstimate57,
    TVEstimate58,
    TVEstimate59,
    TVEstimate60,
    TVEstimate61,
    TVEstimate62,
    TVEstimate63,
    TVEstimate64,
    TVEstimate65,
    TVEstimate66,
    TVEstimate67,
    TVEstimate68,
    TVEstimate69,
    TVEstimate70,
    TVEstimate71,
    TVEstimate72,
    TVEstimate73,
    TVEstimate74,
    TVEstimate75,
    TVEstimate76,
    TVEstimate77,
    TVEstimate78,
    TVEstimate79,
    TVEstimate80,
    TVEstimate81,
    TVEstimate82,
    TVEstimate83,
    TVEstimate84,
    TVEstimate85,
    TVEstimate86,
    TVEstimate87,
    TVEstimate88,
    TVEstimate89,
    TVEstimate90,
    TVEstimate91,
    TVEstimate92,
    TVEstimate93,
    TVEstimate94,
    TVEstimate95,
    TVEstimate96,
    TVEstimate97,
    TVEstimate98,
    TVEstimate99,
    TVEstimate100
  )
)


#plot the last 50,000 values to ensure accurate values are given

plot(
  10000:100000,
  TVMean[10000:100000],
  type = "l",
  lwd = 1.5,
  ylim = c(min(TVMin[10000:100000]), max(TVMax[10000:100000])),
  xlab = "Iterations",
  ylab = "Upper Bound of TV Estimate"
)

polygon(c(10000:100000, rev(10000:100000)), c(TVMin[10000:100000], rev(TVMax[10000:100000])), col =
          "grey") #creates a shaded plot to indicate confidence region
lines(10000:100000, TVMean[10000:100000], col = "red", lwd = 1.5)
